databases:
  - name: dinamicas_igreja_db
    databaseName: dinamicas_igreja
    user: dinamicas_user
    region: oregon

services:
  - type: web
    name: dinamicas-igreja
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "python start.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: dinamicas_igreja_db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SITE_DOMAIN
        value: "dinamicas.onrender.com"
      - key: SITE_NAME
        value: "Din√¢micas para Igreja"
